### ISSUE TITLE
选择 gpio pin 口的代码有问题

### ISSUE THREAD

**Issue by LinkShen** [Philon/rpi-drivers#1]
https://github.com/Philon/rpi-drivers/blob/d1c55d06ef4bc42ff8dee4c4a9962266a36e752c/01-gpio_led/rgbled.c#L129
这里是不是应该写成 iowrite32(val, gpio + BCM2837_GPIO_FSEL0_OFFSET);

**Comment by philon** [comment]
> 

https://github.com/Philon/rpi-drivers/blob/d1c55d06ef4bc42ff8dee4c4a9962266a36e752c/01-gpio_led/rgbled.c#L13
你说的没错，不过BCM2837_GPIO_FSEL0_OFFSET本来就是0
