### ISSUE TITLE
01-gpio_led 里为啥不用读寄存器的方式获取状态呢？

### ISSUE THREAD

**Issue by comdotwang162** [Philon/rpi-drivers#2]
01-gpio_led 里为啥不用读寄存器的方式获取状态呢？
也就是获取管脚的高低电平

**Comment by philon** [comment]
> 01-gpio_led 里为啥不用读寄存器的方式获取状态呢？
> 也就是获取管脚的高低电平

好想法，不过太久远了，我也不记得当时写的时候脑子里在想啥😄
